### ISSUE TITLE
How to install and build your boilerplate app

### ISSUE THREAD

**Issue by m2hd1** [ReggaePanda/React-Native-Web-TypeScript-Prettier-Boilerplate#906]
Hi @ManAnRuck,

I appreciate your work on this boilerplate. It looks very useful and interesting. 👍

However, I’m having some trouble with the installation and build process. I think it might be due to some incompatible or missing tools.

Could you please specify the required versions of node, python, docker, and any other tools in the description? That would make it easier for me and others to use your boilerplate.

Thank you very much for your help. 🙏

**Comment by ManAnRuck** [comment]
Hi @m2hd1,
sorry, this repository is totally outdated and I have no time to update or to maintain this project anymore.
Maybe you are successful if you search for some tutorials based on https://github.com/ethanneff/react-native-web-typescript

**Comment by m2hd1** [comment]
no worries @ManAnRuck I completely understand, thank you for the link!
